INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (1,'Does the action contribute to reducing poverty levels in the country/community?','sdg1_pov_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (2,'Does the action contribute to bringing access to basic services to the vulnerable sections of the country/society?','sdg1_pov_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (3,'Does the action contribute to building resilience and reducing vulnerability against climate events and resulting social, economic and environmental impacts in the country/ community?', 'sdg1_pov_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (4,'Does the action lead to increased spending by the national government into sectors that accelerate poverty eradication?','sdg1_pov_q4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (5,'Additional number of people living on more than $1.25 per day','sdg1_pov_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (6,'Additional number of people with social security','sdg1_pov_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (7,'Additional resources to implement programmes and policies for poverty reduction','sdg1_pov_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (8,'Additional gender-sensitive policy frameworks at regional and national level to accelerate investment in poverty reduction','sdg1_pov_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (9,' Does the action empower and/or improve the quality of life and income generation of the bottom 40% of the population (at a rate higher than the national average)? ','sdg10_ineq_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (10,'Does the action empower and promote the social, economic and political inclusion of all, irrespective of age, sex, race, ethnicity, origin, religion or economic or other status?' , 'sdg10_ineq_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (11,'Does the action empower and promote inclusion of people with disabilities in economic and social life? ','sdg10_ineq_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (12,'Does the action ensure equal opportunity and reduce inequalities of outcome, including by eliminating discriminatory laws, policies and practices and promoting appropriate legislation, policies and action in this regard?' , 'sdg10_ineq_q4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (13,'Does the action promote greater parity in wages and social protection (e.g.insurance) towards greater equality? ','sdg10_ineq_q5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (14,'Does the action ensure better representation of the country in global decision making process (e.g.give voting rights in international organizations) particularly in the financial and economic context? ','sdg10_ineq_q6\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (15,'Additional policy frameworks at regional and national level to reduce inequality and empower vulnerable groups','sdg10_ineq_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (16,'Additional number of people from vulnerable backgrounds participating in decision-making','sdg10_ineq_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (17,'Additional official development assistance including foreign direct investment for community/country','sdg10_ineq_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (19,'Does the action contribute to ending discrimination against girls / women (e.g.Non - discrimination of employment based on sex)?','sdg5_gen_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (20,'Does the action contribute to ending violence against girls / women (e.g.trafficking or sexual exploitation)?','sdg5_gen_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (21,'Does the action contribute to ending harmful practices against girls / women (e.g.Child marriage, genital mutilation etc.)? ' , 'sdg5_gen_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (22,'Does the action contribute to promoting equal rights to economic resources to women (e.g.ownership of land)?','sdg5_gen_q4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (23,'Does the action contribute to promoting equal rights to reproductive health and reproductive rights (e.g., Use of contraceptives, access to health services etc.)?' , 'sdg5_gen_q5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (24,'Number of women employed under the action','sdg5_gen_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (25,'Number of women trained under the action','sdg5_gen_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (26,'Number of women selected for decision making position (e.g.Senior managers, community leaders, etc.', 'sdg5_gen_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (27,'Number of women provided with access to modern technology and/or finance (e.g.microfinance, mobile phones, etc.)' , 'sdg5_gen_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (28,'Does the action promote access to affordable, reliable and modern clean technology / services?' , 'sdg7_ind_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (29,'Does the action promote the growth of small and medium sized enterprises (SMEs) and provide them appropriate support (e.g.affordable loans)?','sdg9_ind_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (30,'Does the action enable industries to pursue resource efficient business practice and greater adoption of clean technologies?','sdg9_ind_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (31,'Does the action facilitate the development of sustainable and resilient infrastructure through enhanced financial, technological and technical support?' , 'sdg9_ind_q4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (32,'Does the action promote a culture for innovation through enhanced scientific research and development and investments in new thinking, models and ways of doing business and value addition?' , 'sdg9_ind_q5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (33,'Does the action promote the development, transfer, dissemination and diffusion of environmentally sound technologies?' , 'sdg17_ind_q6\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (34,'Does the action promote effective and targeted capacity-building to support national plans for implementing the SDGs?','sdg17_ind_q7\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (35,'Does the action promote access to adequate, safe and affordable housing?' , 'sdg11_ind_q8\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (36,'Investments in industrial activity under the action (large)','sdg9_ind_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (37,'Investments in industrial activity under the action (SME)','sdg9_ind_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (38,'Investments in micro and one - person enterprises','sdg9_ind_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (39,'Investments in research and development','sdg9_ind_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (40,'Investments in intellectual property rights','sdg9_ind_data5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (41,'Investments in pilot research projects','sdg9_ind_data6\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (42,'Investments in transport sector - Road','sdg9_ind_data7\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (43,'Investments in transport sector - Rail','sdg9_ind_data8\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (44,'Investments in transport sector - Sea and waterways','sdg9_ind_data9\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (45,'Investments in transport sector - Air','sdg9_ind_data10\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (46,'Investments in waste water systems','sdg6_ind_data11\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (47,'Investments in solid waste management systems','sdg12_ind_data12\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (48,'Investments in landfill sites and municipal waste','sdg12_ind_data13\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (49,'Investments in industrial waste management systems','sdg12_ind_data14\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (50,'Investments in climate and disaster risk management (e.g.sea walls)','sdg13_ind_data15\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (51,'Investments in public climate risk reduction infrastructure (e.g.stormwater protection)','sdg13_ind_data16\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (52,'Investments in emergency services (e.g.flooding)','sdg13_ind_data17\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (53,'Investments in water treatment/purification facilities','sdg6_ind_data18\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (54,'Investments in irrigation systems','sdg6_ind_data19\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (55,'Investments in water supply systems (e.g., borewells, pipelines)' , 'sdg6_ind_data20\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (56,'Investments in toilets','sdg6_ind_data21\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (57,'New capacity added - renewable energy ','sdg7_ind_data22\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (58,'New investments - power generation','sdg7_ind_data23\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (59,'New investments - transmission and distribution','sdg7_ind_data24\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (60,'Renewable as % of total capacity','sdg7_ind_data25\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (61,'Reduction in fossil fuel imports','sdg7_ind_data26\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (62,'Additional households with access to clean energy','sdg7_ind_data27\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (63,'Additional metered connections','sdg7_ind_data28\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (64,'Additional villages with access to grid','sdg7_ind_data29\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (65,'Additional units of housing (high, medium, low - income)' , 'sdg11_ind_data30\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (66,'Investment in housing','sdg11_ind_data31\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (67,'Slum rehabilitation','sdg11_ind_data32\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (68,'Investment in slum rehabilitation','sdg11_ind_data33\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (69,'Investment in green/resources - efficient buildings','sdg11_ind_data34\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (70,'Does the action lead to reduction in air pollution beyond greenhouse gas emissions reduction?','sdg3_env_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (71,'Does the action lead to reduction in water pollution (including reduction in marine pollution in seas and oceans)?','sdg14_env_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (72,'Does the action lead to reduction in negative impacts on biodiversity and ecosystems (including forests, soil erosion, and other living creatures)?' , 'sdg15_env_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (73,'Does the action promote environmentally sound management of waste as per international best practices that reducing impacts on air, water and land?' , 'sdg12_env_q4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (74,'Is the action part of a long term framework programme / policy (international, national, sectoral etc.) to promote sustainable consumption / production?' , 'sdg12_env_q5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (75,'Does the action substantially reduce waste generation through prevention, reduction, recycling, reuse - ideally in the industrial and economic context (e.g.circular economy)?' , 'sdg9_env_q6\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (76,'Does the action promote a culture for innovation through enhanced scientific research and development and investments in new thinking, models and ways of doing business and value addition?' , 'sdg9_env_q7\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (77,'Reduction in Sox','sdg3_env_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (78,'Reduction in Nox','sdg3_env_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (79,'Reduction in Suspended Particular Matter (SPM)','sdg3_env_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (80,'Reduction in Volatile Organic Compound (VOC)','sdg3_env_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (81,'Reduction in Particulate Matter (PM)','sdg3_env_data5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (82,'Reduction in chemical oxygen demand (COD)','sdg6_env_data6\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (83,'Reduction in biochemical oxygen demand (BOD)','sdg6_env_data7\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (84,'Reduction in bacteria and coliforms','sdg6_env_data8\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (85,'Reduction in marine pollution','sdg14_env_data9\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (86,'Reduction in sea/ocean acidification','sdg14_env_data10\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (87,'Reduction in sustainable fishing','sdg14_env_data11\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (88,'Reduction in coastal/marine area under conservation','sdg14_env_data12\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (89,'Avoided deforestation','sdg15_env_data13\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (90,'Afforestation (new forest added)','sdg15_env_data14\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (91,'Avoided soil erosion','sdg15_env_data15\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (92,'Additionally protected endangered species','sdg15_env_data16\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (93,'Additionally protected reserves','sdg15_env_data17\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (94,'Additional material recycled','sdg12_env_data18\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (95,'Additional material composted','sdg12_env_data19\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (96,'Additional material directed from uncontrolled landfill/incineration to controlled landfill or incineratoin','sdg12_env_data20\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (97,'Additional e - waste recycled/disposed of appropriately','sdg12_env_data21\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (98,'Additional industrial waste water treated appropriately','sdg6_env_data22\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (99,'Does the action contribute to creating new employment opportunities including for women, youth and members of poor and vulnerable sections of the society?' , 'sdg8_emp_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (100,'Does the action promote economic growth in the community/country and/or in higher levels of economic productivity?','sdg8_emp_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (101,'Does the action promote innovation, entrepreneurship and growth of SMEs and micro enterprises?' , 'sdg8_emp_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (102,'Number of new jobs created (total)','sdg8_emp_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (103,'Number of new jobs created for people with disabilities','sdg8_emp_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (104,'Number of new jobs created for poor and vulnerable sections','sdg8_emp_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (105,'Number of new jobs created for specialized skills (e.g.technical)','sdg8_emp_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (106,'Number of new jobs created for senior positions (e.g.managers)','sdg8_emp_data5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (107,'Migration avoided due to new jobs created (people)','sdg8_emp_data6\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (108,'Employees with access to employment benefits (e.g.pension)','sdg8_emp_data7\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (109,'Additional income generated in public sector employment','sdg8_emp_data8\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (110,'Additional income generated in private sector employment','sdg8_emp_data9\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (111,'Does the action promote access to pre - primary education (below 6 years)for girls and boys?','sdg4_edu_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (112,'Does the action promote access to primary and secondary education(7-18 years) for girls and boys?','sdg4_edu_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (113,'Does the action promote opportunities for girls and boys to access quality technical, vocational and tertiary education including university?' , 'sdg4_edu_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (114,'Does the action promote access to education for people with disabilities?','sdg4_edu_q4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (115,'Does the action promote access to education for people with vulnerable background including indigenious people and people with low income?','sdg4_edu_q5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (116,'Additional enrollment in primary education (7-12 years)','sdg4_edu_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (117,'Additional enrollment in secondary education (13-18 years)','sdg4_edu_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (118,'Additional enrollment in vocational, university or tertiary institutions' , 'sdg4_edu_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (119,'Additional number of teachers/trainers trained','sdg4_edu_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (120,'Additional scholarships provided','sdg4_edu_data5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (121,'Does the action contribute to ending levels of hunger and malnourishment in the community/country?','sdg2_food_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (122,'Does the action contribute to promoting equal rights and incomes among indigenous communities, poor farmers, pastoral communities and vulnerable members of the community/society?' , 'sdg2_food_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (123,'New land brought under the cultivation','sdg2_food_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (124,'Additional export of crops, animals etc.' , 'sdg2_food_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (125,'Specific investment towards rural infrastructure (e.g.irrigation canals, water pumping etc.)' , 'sdg2_food_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (126,'Specific investment towards research and development (e.g.agriculture productivity, gene banks, livestock etc.)' , 'sdg2_food_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (127,'Does the action contribute towards access to safe and affordable drinking water?','sdg6_wat_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (128,'Does the action contribute towards access to sanitation and hygiene including for women and girls?','sdg6_wat_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (129,'Does the action contribute towards increased water use efficiency and / or water management system?','sdg6_wat_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (130,'Does the action contribute towards waste and waste water management system including treatment, recycling, reuse etc.?' , 'sdg6_wat_q4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (131,'Additional number of water treatments â€“ facility level','sdg6_wat_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (132,'Additional number of water treatments / filtration - household level (e.g.Household water purification system)','sdg6_wat_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (133,'Additional number of irrigation Systems (e.g.Solar powered irrigation pumps)','sdg6_wat_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (134,'Additional number of direct water supply sources (e.g.Borewells)','sdg6_wat_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (135,'Additional volume of safe water effectively treated / supplied','sdg6_wat_data5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (136,'Does the action lead to lowering maternal deaths during childbirth?','sdg3_hlt_q1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (137,'Does the action lead to lowering child mortality (below 5 years)?','sdg3_hlt_q2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (138,'Does the action lead to reduced risk/impact of epidemics?','sdg3_hlt_q3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (139,'Does the action lead to lowering of non - communicable diseases?','sdg3_hlt_q4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (140,'Does the action lead to lowering deaths from other (non - disease) related causes?','sdg3_hlt_q5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (141,'Number of additional people provided with access to health services','sdg3_hlt_data1\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (142,'Number of additional children vaccinated','sdg3_hlt_data2\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (143,'Number of additional health workers directly employed','sdg3_hlt_data3\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (144,'Number of additional government health programmes organized','sdg3_hlt_data4\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (145,'Number of additional people covered by health insurance or public health system','sdg3_hlt_data5\r');
INSERT INTO `sdg_mapping` (`id`, `question`, `mapping`) VALUES (146,'Number of additional health related infrastructure set - up','sdg3_hlt_data6\r');
