module.exports = {
    // NDC
    NDC_PREFIX:"KEN",
    //roles
    ROLE_USER: "user",
    ROLE_ADMIN: "admin",
    ROLE_NODAL: "nodal",

    // menu group
    MENU_GRP_GHG :"GHG INVENTORY",
    MENU_GRP_NDC : "NDC ACTIONS",
    MENU_GRP_REPORT : "REPORTS",
    MENU_GRP_DATABASE : "DATABASE",
    MENU_GRP_USER : "USER",
    MENU_GRP_APPROVAL : "APPROVAL",
    MENU_GRP_NA : "NA",

    // status
    STATUS_ACTIVE:"active",
    STATUS_UPDATE:"update",
    STATUS_PENDING:"pending",
    STATUS_DISABLED:"disabled",
    STATUS_REJECTED:"rejected",
    STATUS_APPROVED:"approved",
    STATUS_TYPE:[this.STATUS_ACTIVE,this.STATUS_UPDATE,this.STATUS_PENDING,this.STATUS_DISABLED,this.STATUS_REJECTED,this.STATUS_APPROVED],
    // validations
    VALIDATE_NULL: "null",
    VALIDATE_EMPTY_ARRAY: "emptyArray",

    // modules
    MODULE_MITIGATION_INPUT: "MITIGATION_INPUT",
    MODULE_MITIGATION_MONITORING: "MITIGATION_MONITORING",
    MODULE_MITIGATION_MONITORING: "MITIGATION_MONITORING",
    MODULE_FINANCE_INPUT: "FINANCE_INPUT",
    MODULE_FINANCE_MONITORING: "FINANCE_MONITORING",
    MODULE_SDG_INPUT: "SDG_INPUT",
    MODULE_REPORT_MRV_TRACKING: "REPORT_MRV_TRACKING",
    MODULE_SDG_MONITORING: "SDG_MONITORING",
    MODULE_ADAPTATION_INPUT: "ADAPTATION_INPUT",
    MODULE_ADAPTATION_MONITORING: "ADAPTATION_MONITORING",
    MODULES: [this.MODULE_MITIGATION_INPUT,this.MODULE_MITIGATION_MONITORING,this.MODULE_FINANCE_INPUT,this.MODULE_SDG_INPUT,this.MODULE_SDG_MONITORING,this.MODULE_ADAPTATION_INPUT,this.MODULE_ADAPTATION_MONITORING],
    // division
    DIVISION_MITIGATION:"Mitigation",
    DIVISION_CROSS_CUTTING:"Cross-cutting",
    DIVISION_ADAPTATION:"Adaptation",
    DIVISION_ENABLERS:"Enablers",
    // hashing
    SALT_ROUND: 10,
   
 
    
    CRUD_SAVE:'save',
    CRUD_GET:'get',
    CRUD_UPDATE:'update',
    CRUD_DELETE:'delete',
    CRUD_REPORT:'report',

    // reports
    REPORT_TEMPLATE_PATH: "assets/ghg/report/Reporting Template-v1.0.xlsx",
    REPORT_TEMPLATE_TAB: "Table A Summary Table",
    REPORT_SKIP_SUB_SECTOR: ["ReferenceEnergy"],

    // mail template
    MAIL_USER_SIGNUP:"signup-user",
    MAIL_ADMIN_SIGNUP:"signup-admin",
    MAIL_USER_APPROVED:"user-approved",
    MAIL_USER_REJECTED:"user-rejected",
    FORGOT_PASSWORD_OTP:"forgot-password-otp",
    MAIL_DATA_STATE_NEW_RECORD_REVIEWER:"data_state-added-reviewer",
    MAIL_DATA_STATE_RECORD_STATUS_CHANGED_FOR_USER:"data_state_status_changed_user",
    MAIL_DATA_STATE_RECORD_STATUS_CHANGED_FOR_REVIEWER:"data_state_status_changed_reviewer",
    MAIL_DATA_STATE_NEW_RECORD_USER:"data_state-added-user",

    //ghg
    INVENTORY_YEAR_START: 1990,
    INVENTORY_YEAR_END: 2050,

    // app constants
    CONST_SECTOR:"sector",
    CONST_CATEGORY:"category",
    CONST_SUB_SECTOR:"subSector",
    CONST_SUB_CATEGORY:"subCategory",
    FILE_STR:"file",
    MANNUAL_STR:"mannual",
    INVENTORY_YEAR_CONFIG_STR:"inventoryYear-config",

    // collectionNames
    COLL_MENU:"menu",

    // Data state Entity format
    GHG_INPUT_ENERGY : "GHG INPUT>ENERGY",
	
	GHG_INPUT_REFERENCE_ENERGY:"GHG INPUT>REFERENCE ENERGY",
	
	GHG_INPUT_FOREST:"GHG INPUT>FOREST LAND",
	
	GHG_INPUT_CROPLAND:"GHG INPUT>CROPLAND",
	
	GHG_INPUT_GRASSLAND:"GHG INPUT>GRASSLAND",
	
	GHG_INPUT_WETLANDS:"GHG INPUT>WETLANDS",
	
	GHG_INPUT_SETTLEMENTS:"GHG INPUT>SETTLEMENTS",
	
	GHG_INPUT_OTHER_LAND :  "GHG INPUT>OTHER LAND",
	
	GHG_INPUT_ENTERIC:"GHG INPUT>ENTERIC FERMENTATION",
	
	GHG_INPUT_SOLVENT:"GHG INPUT>SOLVENT USE",
	
	GHG_INPUT_SOLID_FUEL :  "GHG INPUT>SOLID FUEL",
	
	GHG_INPUT_INDIRECT_N2O :  "GHG INPUT>INDIRECT N2O",
	
	GHG_INPUT_LUBRICANT :  "GHG INPUT>LUBRICANT",
	
	GHG_INPUT_MANURE_MANAGEMENT :  "GHG INPUT>MANURE MANAGEMENT",
	
	GHG_INPUT_SOLID_WASTE:"GHG INPUT>SOLID WASTE DISPOSAL",
	
	GHG_INPUT_WASTE_BURNING:"GHG INPUT>WASTE BURNING",
	
	GHG_INPUT_INCINERATION:"GHG INPUT>INCINERATION",
	
	GHG_INPUT_WASTE_WATER:"GHG INPUT>WASTE WATER",
	
	GHG_INPUT_BIOLOGICAL:"GHG INPUT>BIOLOGICAL TREATEMENT",
	
	GHG_INPUT_REFRIGERATION:"GHG INPUT>REFRIGERATION",
	
	GHG_INPUT_BIOMASS_BURNING:"GHG INPUT>BIOMASS BURNING",
	
	GHG_INPUT_CEMENT:"GHG INPUT>CEMENT",
	
	GHG_INPUT_RICE:"GHG INPUT>RICE",
	
	GHG_INPUT_LIME:"GHG INPUT>LIME",
	GHG_INPUT_GAS:"GHG INPUT>NATURAL GAS",
	GHG_INPUT_UREA:"GHG INPUT>UREA",
	GHG_INPUT_DIRECT_EMISSION:"GHG INPUT>DIRECT N2O EMMISION SOIL",
	GHG_INPUT_INDIRECT_EMISSION:"GHG INPUT>INDIRECT N2O EMMISION SOIL",
	GHG_INPUT_GLASS:"GHG INPUT>GLASS",
	GHG_INPUT_CARBONATE:"GHG INPUT>CARBONATE",
	GHG_INPUT_SODA_ASH:"GHG INPUT>SODA_ASH",
	GHG_INPUT_INCINERATION:"GHG INPUT>INCINERATION",
    
    // NDC type
	NDC_PROJECT:"Project",
    MITIGATION_INPUT:"MITIGATION INPUT",
    MITIGATION_MONITORING : "MITIGATION MONITORING",
	FINANCE_INPUT : "FINANCE INPUT",
	FINANCE_DETAILED_BUDGET : "FINANCE DETAILED BUDGET",
	FINANCE_MONITORING : "FINANCE MONITORING",
	SDG_INPUT : "SDG INPUT",
	SDG_MONITORING : "SDG MONITORING",
	ADAPTATION_INPUT : "ADAPTATION INPUT",
	ADAPTATION_MONITORING : "ADAPTATION MONITORING",
    NDC_SECTOR_SPLIT:"{#}",
    // MENU_ID


    // Internal api calls
    API_DATABASE_IPPU_GWP: "/database/ippu/gwp",
    API_DATABASE_AFOLU_LIVE_STOCK_EMISSION_FACTOR: "/database/afolu/emissionFactor",
    API_DATABASE_AFOLU_LIVE_STOCK_POPULATION: "/database/afolu/population",
    API_DATABASE_IPPU_EMISSION_FACTOR: "/database/ippu/emissionFactor",
    API_DATABASE_IPPU_GET_GWP: "/database/ippu/gwp",
    API_DATABASE_ENERGY_EMISSION_FACTOR: "/database/energy/emissionFactor",
    API_DATABASE_ENERGY_FUGITIVE: "/database/energy/fugitive",
    API_NDC_SECTOR_MAPPING: "/shared/ndc/sectorMapping",
    API_DATA_STATE_NDC: "/data-state/ndc",
    API_APP_DATA: "/shared/appdata",

        // ghg api calls
    API_GHG_SECTOR_MAPPING : "/ghg/sectorDetails",
    


}