export enum ChartType {
  TOTAL_PROGRAMS = "TOTAL_PROGRAMS",
  TOTAL_PROGRAMS_SECTOR = "TOTAL_PROGRAMS_SECTOR",
  TOTAL_CREDITS = "TOTAL_CREDITS",
  TOTAL_CREDITS_CERTIFIED = "TOTAL_CREDITS_CERTIFIED",
  TOTAL_CREDITS_SECTOR = "TOTAL_CREDITS_SECTOR",
  PROGRAMME_LOCATIONS = "PROGRAMME_LOCATIONS",
  TRANSFER_LOCATIONS = "TRANSFER_LOCATIONS",
  PROGRAMME_DETAILS = "PROGRAMME_DETAILS",
}
