export enum CreditStatType {
  CREDIT_STATS_BALANCE = "creditBalance",
  CREDIT_STATS_TRANSFERRED = "creditTransferred",
  CREDIT_STATS_RETIRED = "creditRetired",
  CREDIT_STATS_ISSUED = "creditIssued",
  CREDIT_STATS_ESTIMATED = "creditEst",
  CREDIT_STATS_FROZEN = 'creditFrozen',
  CREDIT_CERTIFIED_BALANCE = "creditBalance",
  CREDIT_CERTIFIED_TRANSFERRED = "creditTransferred",
  CREDIT_CERTIFIED_RETIRED = "creditRetired",
  CREDIT_CERTIFIED_ISSUED = "creditIssued",
  CREDIT_CERTIFIED = "creditBalance",
  CREDIT_UNCERTIFIED = "creditBalance",
  CREDIT_REVOKED = "creditBalance",
}
