export enum TypeOfMitigation {
    AGRICULTURE = 'Agriculture',
    BIOMASS_ENERGY = 'BiomassEnergy',
    CCS = 'CCS',
    CEMENT = 'Cement',
    COAL_MINE = 'Coal/Mine',
    EE_HOUSEHOLDS = 'EEHouseholds',
    EE_INDUSTRY = 'EEIndustry',
    EE_OWN_GENERATION = 'EEOwnGeneration',
    EE_SERVICE = 'EEService',
    EE_SUPPLY_SIDE = 'EESupplySide',
    ENERGY_DISTRIBUTION = 'EnergyDistribution',
    FORESTRY = 'Forestry',
    FOSSIL_FUEL = 'FossilFuel',
    FUGITIVE = 'Fugitive',
    GEOTHERMAL = 'Geothermal',
    HFC_PFCS_SF6 = 'HFC_PFCs_SF6',
    HYDRO = 'Hydro',
    LANDFILLS = 'Landfills',
    MARINE = 'Marine',
    METHANE_AVOIDANCE = 'MethaneAvoidance',
    N20 = 'N20',
    SOLAR = 'Solar',
    TRANSPORT = 'Transport',
    WIND = 'Wind'
}

export const mitigationTypeList: any = [
  'Agriculture',
  'BiomassEnergy',
  'CCS',
  'Cement',
  'Coal/Mine',
  'EEHouseholds',
  'EEIndustry',
  'EEOwnGeneration',
  'EEService',
  'EESupplySide',
  'EnergyDistribution',
  'Forestry',
  'FossilFuel',
  'Fugitive',
  'Geothermal',
  'HFC_PFCs_SF6',
  'Hydro',
  'Landfills',
  'Marine',
  'MethaneAvoidance',
  'N20',
  'Solar',
  'Transport',
  'Wind'
 ]

export const sectorMitigationTypesListMapped: any = {
  Energy: [
    'BiomassEnergy',
    'Coal/Mine',
    'EEHouseholds',
    'EEIndustry',
    'EEOwnGeneration',
    'EEService',
    'EESupplySide',
    'EnergyDistribution',
    'FossilFuel',
    'Geothermal',
    'Hydro',
    'Solar',
    'Wind',
  ],
  Health: [...mitigationTypeList],
  Education: [...mitigationTypeList],
  Transport: ['Transport'],
  Manufacturing: [
    'Cement',
    'CCS',
    'HFC_PFCs_SF6',
  ],
  Hospitality: [...mitigationTypeList],
  Forestry: ['Forestry'],
  Waste: [
    'Landfills',
    'Fugitive',
    'MethaneAvoidance',
  ],
  Agriculture: ['Agriculture'],
  Other: [
    'Marine',
    'N20',
  ],
};