INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (299,'Does the action increase number of households and entities benefiting from devolved adaptive services, including National Safety Net Programme and County Climate Change Funds (CCCFs)?','adp_DRM_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (300,'Does the action improve ability of people to cope with drought?','adp_DRM_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (301,'Does the action improve ability of people to cope with floods?','adp_DRM_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (302,'Does the action enhance crop productivity?','adp_FNS_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (303,'Does the action enhance productivity in the livestock sector?','adp_FNS_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (304,'Does the action enhance productivity in the fisheries sector?','adp_FNS_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (305,'Does the action diversify livelihoods to adjust to a changing climate?','adp_FNS_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (306,'Does the action lead to increased annual per capita water availability?','adp_WBE_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (307,'Does the action promote water efficiency?','adp_WBE_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (308,'Does the action improve access to good quality water?','adp_WBE_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (309,'Does the action improve climate resilience of coastal communities?','adp_WBE_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (310,'Does the action promote afforestation and reforestion degraded?','adp_FWT_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (311,'Does the action implement initiatives to reduce deforestation and forest degradation?','adp_FWT_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (312,'Does the action restore degraded landscapes (ASALs and rangelands)?','adp_FWT_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (313,'Does the action promote sustainable timber production on privately-owned land?','adp_FWT_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (314,'Does the action conserve land area for wildlife?','adp_FWT_q5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (315,'Does the action reduce Incidence of malaria and other vector-borne disease?','adp_HSS_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (316,'Does the action promote recycling to divert collected waste away from disposal sites?','adp_HSS_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (317,'Does the action control flooding in human settlement?','adp_HSS_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (318,'Does the action promote green buildings?','adp_HSS_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (319,'Does the action enhance energy efficiency?','adp_ETP_q5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (320,'Does the action improve water use and resource efficiency?','adp_ETP_q6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (321,'Does the action optimise manufacturing and production processes?','adp_ETP_q7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (322,'Does the action promote industrial symbiosis in industrial zones?','adp_ETP_q8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (323,'Does the action increase renewable energy for electricity generation?','adp_ETP_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (324,'Does the action promote the transition to clean cooking with alternative clean fuels in urban areas; and clean biomass (charcoal and wood) cookstoves and alternatives in rural areas?','adp_ETP_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (325,'Does the action encourage low-carbon technologies in the aviation and maritime sectors?','adp_ETP_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (326,'Does the action climate proof transport infrastructure?','adp_ETP_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (327,'Number of beneficiaries of social protection mechanisms (food and cash transfers)','adp_DRM_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (328,'Number of households benefitting from Hunger Net Safety Programme ','adp_DRM_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (329,'Amount of funding allocated to climate change actions through CCCFs in Counties with climate fund regulations','adp_DRM_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (330,'Number of recipients of Climate Information Services','adp_DRM_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (331,'Number of early warning systems for droughts','adp_DRM_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (332,'Number of early warning systems for floods','adp_DRM_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (333,'Number of farmers with crop insurance','adp_FNS_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (334,'Number of farmers accessing agriculture input subsidies','adp_FNS_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (335,'Number of institutions harvesting water','adp_FNS_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (336,'Percentage of pre- and post-harvest losses','adp_FNS_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (337,'Acreage under irrigation','adp_FNS_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (338,'Hectares of rangeland re-seeded','adp_FNS_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (339,'Million cubic meters (MCM) of water storage in (Arid and Semi Arid Land) ASALs','adp_FNS_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (340,'Numbers of farmers accessing livestock insurance','adp_FNS_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (341,'Number of cages for fish farming','adp_FNS_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (342,'Number of fish ponds','adp_FNS_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (343,'Number of farmers using low-carbon recirculating aquaculture systems','adp_FNS_data11');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (344,'Number of households supported to diversify value chains','adp_FNS_data12');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (345,'Per capita water availability','adp_WBE_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (346,'Number of dams','adp_WBE_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (347,'Number of sub-catchment management plans','adp_WBE_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (348,'Number of climate-proofed water harvesting, flood control and water storage infrastructure','adp_WBE_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (349,'Number of farm ponds','adp_WBE_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (350,'Number of hectares with access to water pans and ponds','adp_WBE_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (351,'Percentage of people with access to good quality water','adp_WBE_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (352,'Number of deep/offshore fishing vessels','adp_WBE_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (353,'Hectares of mangroves restored/rehabilitated','adp_WBE_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (354,'Percentage of coastal and marine areas conserved','adp_WBE_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (355,'Hectares of land afforested or reforested','adp_FWT_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (356,'Number of TIPs signed','adp_FWT_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (357,'Number of hectares of forest land protected','adp_FWT_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (358,'Number of hectares of restored degraded landscapes','adp_FWT_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (359,'Number of hectares of private-sector based plantations','adp_FWT_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (360,'Percentage of terrestrial and inland water areas conserved','adp_FWT_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (361,'Number of hectares of wildlife conservation areas','adp_FWT_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (362,'Number of incidents of human-wildlife conflict','adp_FWT_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (363,'Percentage of dispersal areas and migratory pathways secured','adp_FWT_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (364,'Malaria incidence per 1,000 population','adp_HSS_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (365,'Percentage of waste diverted from disposal sites towards recycling practices','adp_HSS_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (366,'Number of flood ways constructed in urban centres','adp_HSS_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (367,'Number of green building codes developed and approved','adp_HSS_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (369,'Number of companies participating in water efficiency initiatives','adp_ETP_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (371,'Number of industrial parks adopting industrial symbiosis practices','adp_ETP_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (372,'Additional generation capacity in MW of renewable electricity added to the grid','adp_ETP_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (373,'Number of households using LPG','adp_ETP_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (374,'Number of households with improved biomass cookstoves','adp_ETP_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (375,'Number of berths with shore power ','adp_ETP_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (376,'Number of fuel efficient aircraft purchased','adp_ETP_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (377,'Number of kilometres of roads that are climate proofed','adp_ETP_data6');
