export enum StatType {
    TOTAL_PROGRAMS = 'TOTAL_PROGRAMS',
    CREDIT_ISSUED = 'CREDIT_ISSUED',
    CREDIT_CERTIFIED = 'CREDIT_CERTIFIED',
    PROGRAMS_BY_STATUS = 'PROGRAMS_BY_STATUS',
    PROGRAMS_BY_SECTOR = 'PROGRAMS_BY_SECTOR',
    PROGRAMS_BY_SUB_SECTOR = 'PROGRAMS_BY_SUB_SECTOR',
    CREDIT_ISSUED_TIME = 'CREDIT_ISSUED_TIME',
    CREDIT_CERTIFIED_TIME = 'CREDIT_CERTIFIED'
}