export enum ProgrammeManagementColumns {
  title = 'title',
  company = 'company',
  sector = 'sector',
  currentStage = 'currentStage',
  creditIssued = 'creditIssued',
  creditBalance = 'creditBalance',
  creditTransferred = 'creditTransferred',
  certifierId = 'certifierId',
  serialNo = 'serialNo',
  action = 'action',
  emissionReductionExpected = 'emissionReductionExpected',
  emissionReductionAchieved = 'emissionReductionAchieved',
  emissionReductionAchievedandCreditIssued = 'emissionReductionAchievedandCreditIssued',
}
