export enum ProjectStatus {
  PROPOSAL_STAGE = "PROPOSAL_STAGE",
  PROCUREMENT_STAGE = "PROCUREMENT_STAGE",
  CONSTRUCTION_STAGE = "CONSTRUCTION_STAGE",
  INSTALLATION_STAGE = "INSTALLATION_STAGE",
}
