export enum SectoralScope {
  'Energy Industries (Renewable – / Non-Renewable Sources)' = '1',
  'Energy Distribution' = '2',
  'Energy Demand' = '3',
  'Manufacturing Industries' = '4',
  'Chemical Industries' = '5',
  'Construction' = '6',
  'Transport' = '7',
  'Mining/Mineral Production' = '8',
  'Metal Production' = '9',
  'Fugitive Emissions From Fuels (Solid, Oil and Gas)' = '10',
  'Fugitive Emissions From Production and Consumption of Halocarbons and Sulphur Hexafluoride' = '11',
  'Solvent Use' = '12',
  'Waste Handling and Disposal' = '13',
  'Afforestation and Reforestation' = '14',
  'Agriculture' = '15',
}

export const EmissionSubSectorsToSectoralScopeMap: any = {
  fuelCombustionActivities: '1',
  fugitiveEmissionsFromFuels: '10',
  carbonDioxideTransportStorage: '3',
  mineralIndustry: '8',
  chemicalIndustry: '5',
  metalIndustry: '9',
  nonEnergyProductsFuelsSolventUse: '12',
  electronicsIndustry: '4',
  productUsesSubstOzoneDepletingSubs: '11',
  otherProductManufactureUse: '4',
  otherIndustrialProcessesProductUse: '4',
  livestock: '15',
  land: '14',
  aggregateNonCo2SourcesLand: '15',
  otherAgricultureForestryOtherLandUse: '15',
  solidWasteDisposal: '13',
  biologicalTreatmentSolidWaste: '13',
  incinerationOpenBurningWaste: '13',
  wastewaterTreatmentDischarge: '13',
  otherWaste: '13',
  indirectN2oEmissions: '15',
  other: '15',
}

export const EmissionSubSectorsPathMap: any = {
  fuelCombustionActivities: 'energyEmissions.fuelCombustionActivities',
  fugitiveEmissionsFromFuels: 'energyEmissions.fugitiveEmissionsFromFuels',
  carbonDioxideTransportStorage: 'energyEmissions.carbonDioxideTransportStorage',
  mineralIndustry: 'industrialProcessesProductUse.mineralIndustry',
  chemicalIndustry: 'industrialProcessesProductUse.chemicalIndustry',
  metalIndustry: 'industrialProcessesProductUse.metalIndustry',
  nonEnergyProductsFuelsSolventUse: 'industrialProcessesProductUse.nonEnergyProductsFuelsSolventUse',
  electronicsIndustry: 'industrialProcessesProductUse.electronicsIndustry',
  productUsesSubstOzoneDepletingSubs: 'industrialProcessesProductUse.productUsesSubstOzoneDepletingSubs',
  otherProductManufactureUse: 'industrialProcessesProductUse.otherProductManufactureUse',
  otherIndustrialProcessesProductUse: 'industrialProcessesProductUse.other',
  livestock: 'agricultureForestryOtherLandUse.livestock',
  land: 'agricultureForestryOtherLandUse.land',
  aggregateNonCo2SourcesLand: 'agricultureForestryOtherLandUse.aggregateNonCo2SourcesLand',
  otherAgricultureForestryOtherLandUse: 'agricultureForestryOtherLandUse.other',
  solidWasteDisposal: 'waste.solidWasteDisposal',
  biologicalTreatmentSolidWaste: 'waste.biologicalTreatmentSolidWaste',
  incinerationOpenBurningWaste: 'waste.incinerationOpenBurningWaste',
  wastewaterTreatmentDischarge: 'waste.wastewaterTreatmentDischarge',
  otherWaste: 'waste.other',
  indirectN2oEmissions: 'other.indirectN2oEmissions',
  other: 'other.other',
}
