truncate table adaptation_mapping;

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (301,'Does the action increase number of households and entities benefiting from devolved adaptive services?','adp_DRM_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (302,'Does the action improve ability of people to cope with drought?','adp_DRM_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (303,'Does the action improve ability of people to cope with floods?','adp_DRM_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (304,'Does the action increase information sharing among local communities?','adp_DRM_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (305,'Does the action control flooding in human settlement?','adp_DRM_q5');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (311,'Does the action enhance crop productivity?','adp_FNS_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (312,'Does the action diversify livelihoods to adjust to a changing climate?','adp_FNS_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (313,'Does the action promote the transition to clean cooking with alternative clean fuels in urban areas; and clean biomass (charcoal and wood) cookstoves and alternatives in rural areas?','adp_FNS_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (314,'Does the action improve digital marketing?','adp_FNS_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (315,'Does the action improve land productivity and promote alternatives to livelihoods?','adp_FNS_q5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (316,'Does the action improve watershed management?','adp_FNS_q6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (317,'Does the action improve ability of farmers to cope with droughts and floods?','adp_FNS_q7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (318,'Does the action improve community safety nets and diversify livelihoods?','adp_FNS_q8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (319,'Does the action improve water supply to wildlife?','adp_FNS_q9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (320,'Does the action protect and improve watersheds management?','adp_FNS_q10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (321,'Does the action increase awareness among the local communities?','adp_FNS_q11');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (322,'Does the action lead to forest conservation during droughts?','adp_FNS_q12');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (323,'Does the action enhance  productivity in the livestock sector?','adp_FNS_q13');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (324,'Does the action control carry capacity?','adp_FNS_q14');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (325,'Does the action improve alternative livelihood options with a focus on vulnerable households?','adp_FNS_q15');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (326,'Does the action enhance productivity in the fisheries sector?','adp_FNS_q16');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (331,'Does the action lead to increased annual per capita water availability?','adp_WBE_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (332,'Does the action promote water efficiency?','adp_WBE_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (333,'Does the action improve access to good quality water?','adp_WBE_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (334,'Does the action improve water use and resource efficiency?','adp_WBE_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (335,'Does the action improve conservation of wetlands?','adp_WBE_q5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (336,'Does the action improve water use and resource efficiency?','adp_WBE_q6');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (341,'Does the action promote afforestation and reforestion of degraded land?','adp_FWT_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (342,'Does the action implement initiatives to reduce deforestation and forest degradation?','adp_FWT_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (343,'Does the action restore degraded landscapes?','adp_FWT_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (344,'Does the action promote sustainable timber production on privately-owned land?','adp_FWT_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (345,'Does the action conserve land area for wildlife?','adp_FWT_q5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (346,'Does the action improve ability of people to cope with Forest Fires?','adp_FWT_q6');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (351,'Does the action improve health sector capacities?','adp_HSS_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (352,'Does the action promote research on climate change and health?','adp_HSS_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (353,'Does the action improve ability of people to cope with Health Hazards?','adp_HSS_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (354,'Does the action increase resilience of the health systems?','adp_HSS_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (355,'Does the action reduce Incidence of malaria and other vector-borne disease?','adp_HSS_q5');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (361,'Does the action increase renewable energy for electricity generation?','adp_ETP_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (362,'Does the action enhance energy efficiency?','adp_ETP_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (363,'Does the action enhance energy investments?','adp_ETP_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (364,'Does the action increase resilience of the  energy infrastructure?','adp_ETP_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (365,'Does the action increase access to energy?','adp_ETP_q5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (366,'Does the action increase fuel efficiency?','adp_ETP_q6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (367,'Does the action promote the use of clen energy solutions?','adp_ETP_q7');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (371,'Does the action promote recycling to divert collected waste away from disposal sites?','adp_IND_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (372,'Does the action promote green buildings?','adp_IND_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (373,'Does the action optimise manufacturing and production processes?','adp_IND_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (374,'Does the action promote industrial symbiosis in industrial zones?','adp_IND_q4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (375,'Does the action improve building and construction codes?','adp_IND_q5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (376,'Does the action climate proof transport infrastructure?','adp_IND_q6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (377,'Does the action increase productivity through irrigation?','adp_IND_q7');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (381,'Does the action empower local development committees?','adp_HMS_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (382,'Does the action promote hygiene and sanitation?','adp_HMS_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (383,'Does the action promote hygiene and sanitation?','adp_HMS_q3');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (391,'Does the action promote community-based adaptation and ecosystem based adaptation?','adp_TOR_q1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (392,'Does the action promote tourism development?','adp_TOR_q2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (393,'Does the action promote tourism development?','adp_TOR_q3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (394,'Does the action conserve the natural environment and promote eco-tourism?','adp_TOR_q4');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (401,'Number of beneficiaries of social protection mechanisms (food and cash transfers)','adp_DRM_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (402,'Number of flood ways constructed in urban centres','adp_DRM_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (403,'Amount of funding allocated to climate change actions (USD)','adp_DRM_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (404,'Number of recipients of Climate Information Services','adp_DRM_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (405,'Number of early warning systems for droughts Strengthened/Established','adp_DRM_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (406,'Number of early warning systems for floods Strengthened/Established','adp_DRM_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (407,'Number of Community DRM Committees established','adp_DRM_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (408,'Number of Community DRM Strategies and plans developed','adp_DRM_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (409,'Number of Community based EW and DRR set for flood and drought','adp_DRM_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (410,'Number of Community EW & DRR Trainings conducted','adp_DRM_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (411,'Number of households benefitted','adp_DRM_data11');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (421,'Number of farmers with crop insurance','adp_FNS_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (422,'Number of farmers accessing agriculture input subsidies','adp_FNS_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (423,'Number of institutions harvesting water','adp_FNS_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (424,'Percentage of pre- and post-harvest losses','adp_FNS_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (425,'Acreage under irrigation','adp_FNS_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (426,'Number of households supported to diversify value chains','adp_FNS_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (427,'Number of households using LPG','adp_FNS_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (428,'Number of households with improved biomass cookstoves','adp_FNS_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (429,'Number of E-commerce market places','adp_FNS_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (430,'Number of farmer management solutions','adp_FNS_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (431,'Number of digital communication tools adopted','adp_FNS_data11');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (432,'Number of digital financial services adopted','adp_FNS_data12');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (433,'Hectares of agricultural land agroforested','adp_FNS_data13');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (434,'Number of farmers practicing agroforestry','adp_FNS_data14');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (435,'Production in Kgs per hectare achieved','adp_FNS_data15');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (436,'Reduced number of malnourished children','adp_FNS_data16');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (437,'Hectares restored','adp_FNS_data17');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (438,'Number of community stakeholders trained on reforestation practices and conservation systems','adp_FNS_data18');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (439,'Number of watershed committees established for sustainable management of catchment areas','adp_FNS_data19');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (440,'Number of farmers receiving climate information','adp_FNS_data20');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (441,'Number of early warning systems for droughts Strengthened/Established','adp_FNS_data21');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (442,'Hectares of land afforested using multi-use forest species','adp_FNS_data22');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (443,'Hectares of degraded landscapes restored','adp_FNS_data23');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (444,'Number of Community stakeholders trained','adp_FNS_data24');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (445,'Number of water points established','adp_FNS_data25');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (446,'Percentage of protected areas with water points','adp_FNS_data26');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (447,'Number of forest reserves mapped','adp_FNS_data27');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (448,'Number of Community based forest management (CBFM) or participatory management established','adp_FNS_data28');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (449,'Number of Forest policies and measures developed and institutional arrangements established','adp_FNS_data29');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (450,'Number of public awareness campaigns on climate change','adp_FNS_data30');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (451,'Number of communication tools that incorporate climate change adaptation','adp_FNS_data31');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (452,'Number of urban adaptation best practices disseminated','adp_FNS_data32');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (453,'Number of firebreaks constructed','adp_FNS_data33');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (454,'Proportion of forest managers taking action on adaptation','adp_FNS_data34');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (455,'Hectares of rangeland re-seeded','adp_FNS_data35');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (456,'Million cubic meters (MCM) of water storage','adp_FNS_data36');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (457,'Numbers of farmers accessing livestock insurance','adp_FNS_data37');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (458,'Number of rangelands mapped','adp_FNS_data38');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (459,'Hectares of rangeland mapped','adp_FNS_data39');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (460,'Number of supply chain for fisheries industry enhanced','adp_FNS_data40');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (461,'Percentage of famers and fisherfolk with access to financial services','adp_FNS_data41');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (462,'Number of cages for fish farming','adp_FNS_data42');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (463,'Number of fish ponds','adp_FNS_data43');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (464,'Number of farmers using low-carbon recirculating aquaculture systems','adp_FNS_data44');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (471,'Per capita water availability','adp_WBE_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (472,'Number of dams','adp_WBE_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (473,'Number of sub-catchment management plans','adp_WBE_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (474,'Number of climate-proofed water harvesting, flood control and water storage infrastructure','adp_WBE_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (475,'Number of farm ponds','adp_WBE_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (476,'Number of hectares with access to water pans and ponds','adp_WBE_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (477,'Percentage of people with access to good quality water','adp_WBE_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (478,'Number of companies participating in water efficiency initiatives','adp_WBE_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (479,'Number of wetland conserved','adp_WBE_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (480,'Changes in local water balance (inflow/outflow)','adp_WBE_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (481,'Percentage of treated wastewater','adp_WBE_data11');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (491,'Hectares of land afforested or reforested','adp_FWT_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (492,'Number of TIPs signed','adp_FWT_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (493,'Number of hectares of forest land protected','adp_FWT_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (494,'Number of hectares of restored degraded landscapes','adp_FWT_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (495,'Number of hectares of private-sector based plantations','adp_FWT_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (496,'Percentage of terrestrial and inland water areas conserved','adp_FWT_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (497,'Hectares of wildlife conservation areas/number of wildlife reserves established','adp_FWT_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (498,'Number of incidents of human-wildlife conflict','adp_FWT_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (499,'Percentage of dispersal areas and migratory pathways secured','adp_FWT_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (500,'Number of forest monitoring towers established in forested areas','adp_FWT_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (501,'Number of early warning systems for forest fires established','adp_FWT_data11');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (502,'Number of policies  and frameworks in environment and biodiversity that address climate change','adp_FWT_data12');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (503,'Percentage of climate resilient trees','adp_FWT_data13');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (504,'Number of inventories of climate change impacts on biodiversity','adp_FWT_data14');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (511,'Malaria incidence per 1,000 population','adp_HSS_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (512,'Number of policies, plans or programmes introduced or adjusted that mainstream climate risks','adp_HSS_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (513,'Number of people supported to cope with the effects of climate change through the availability of a service or facility','adp_HSS_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (514,'Number of health facilities with climate proof infrastructure','adp_HSS_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (515,'Number of researches conducted on climate change and health','adp_HSS_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (516,'Number of early warning systems for Health Hazards Strengthened/Established','adp_HSS_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (517,'Number of public health officials trained on climate change adaptation','adp_HSS_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (518,'Monitoring and surveillance enhanced','adp_HSS_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (519,'Percentage of climate resilient health infrastructure in the country','adp_HSS_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (520,'Degree of integration of climate change into development planning','adp_HSS_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (521,'Number government staff that have received training on adaptation','adp_HSS_data11');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (531,'Number of energy units (kWh) saved','adp_ETP_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (532,'Energy efficiency addressed in climate change policy (Numbers)','adp_ETP_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (533,'Number of companies participating in energy efficiency initiatives','adp_ETP_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (534,'Number of energy investments enhanced to adopt diversified energy technologies','adp_ETP_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (535,'Number of  people whose livelihoods are supported through the energy investments','adp_ETP_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (536,'Number of new technologies adopted to enhance energy investments','adp_ETP_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (537,'Percentage of new hydroelectric projects that consider future climate risks','adp_ETP_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (538,'Number of Water efficiency measures used in energy generation/extraction','adp_ETP_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (539,'Energy storage capacity','adp_ETP_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (540,'Additional generation capacity in MW of renewable electricity added to the grid','adp_ETP_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (541,'Additional household/people have access to modern energy','adp_ETP_data11');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (542,'Per capita electricity consumption (kWh/Person)','adp_ETP_data12');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (543,'Number of youth and women engaged in the production of non-forest biomass fuel  briquettes','adp_ETP_data13');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (544,'Percentage/number of people producing alternative non forest biomass fuel','adp_ETP_data14');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (545,'Number of companies engaged in the production of non-forest biomass fuel briquettes','adp_ETP_data15');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (546,'Number of policies and frameworks that promote clean energy solutions','adp_ETP_data16');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (547,'Clean energy solutions adopted','adp_ETP_data17');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (551,'Number of green building codes developed and approved','adp_IND_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (552,'Number of companies participating in process optimization initiatives','adp_IND_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (553,'Percentage of waste diverted from disposal sites towards recycling practices','adp_IND_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (554,'Number of industrial parks adopting industrial symbiosis practices','adp_IND_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (555,'Number of ESIA reports on large infrastructural projects recorded','adp_IND_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (556,'Number of ESIA conducted','adp_IND_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (557,'Kilometres of roads that are climate proofed','adp_IND_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (558,'Percentage of transport infrastructure standards revised','adp_IND_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (559,'Increase in agricultural productivity through irrigation of harvested land','adp_IND_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (560,'Number of new major infrastructure projects located in areas at risk','adp_IND_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (561,'Percentage of agricultural land with improved irrigation','adp_IND_data11');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (562,'Increase in the percentage of climate resilient crops being used','adp_IND_data12');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (571,'Number of frameworks for climate change adaptation integrated into WASH investments','adp_HMS_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (572,'Percentage of urban households with access to piped water','adp_HMS_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (573,'Number of people in drought-prone areas with access to safe and reliable water','adp_HMS_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (574,'Percentage of municipalities with local regulations considering adaptation and vulnerability assessment results','adp_HMS_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (575,'Number of urban stakeholders capacitated','adp_HMS_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (576,'Hectares of urban ecosystems managed sustainably','adp_HMS_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (577,'Percentage of poor people in drought prone areas with access to safe and reliable water','adp_HMS_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (578,'Number of local government staff sensitized about climate change issues','adp_HMS_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (579,'Percentage of active climate change adaptation committee members at the local government level','adp_HMS_data9');

INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (591,'Number of policies and frameworks that integrate climate smart tourism','adp_TOR_data1');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (592,'Existence of environmental review procedure for site development','adp_TOR_data2');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (593,'Percentage of new tourism developments that are screened','adp_TOR_data3');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (594,'Percentage of area subject to development control','adp_TOR_data4');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (595,'Number of eco-tourism centres established','adp_TOR_data5');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (596,'Percentage of local people with improved well-being','adp_TOR_data6');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (597,'Number of local residents employed as tour guides out of all tour guides','adp_TOR_data7');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (598,'Number of villages within designated tourism development zones that have received some awareness information about tourism development','adp_TOR_data8');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (599,'Community benefits from tourism','adp_TOR_data9');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (600,'Local community involvement in conservation projects in area','adp_TOR_data12');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (601,'Number of recreational sites established','adp_TOR_data10');
INSERT INTO `adaptation_mapping` (`id`, `question`, `mapping`) VALUES (602,'Percentage of recreational sites resilient to climate change','adp_TOR_data11');